site_name: Darkmatter 18

copyright:  Copyright &copy; 2020 - 2021 Darkmatter18

theme:
  name: 'material'
    custom_dir: docs/overrides/

nav:
  - Introduction: 'index.md'

extra:
  version:
    provider: mike